services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress/:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp_db  # MySQL service as the host
      WORDPRESS_DB_USER: remo
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wp_db
    networks:
      - projekt-netzwerk
    depends_on:
      - wp_db  # Ensures db is started before wordpress

  wp_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: remo
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - projekt-netzwerk

volumes:
  db_data:

networks:
  projekt-netzwerk:
    external: true
