version: '3.8'  # Explicit version for better compatibility

services:
  db:
    image: mariadb:10.7  # Pinned version as you specified
    container_name: mariadb
    restart: unless-stopped  # Better than 'always' for manual stops
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wiki
      MYSQL_USER: remo
      MYSQL_PASSWORD: 1234asdf
      MARIADB_AUTO_UPGRADE: "1"  # Enable automatic upgrades
    volumes:
      - db_data:/var/lib/mysql  # Changed to named volume for better management
    networks:
      - projekt-netzwerk
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    ports:
      - "8081:80"
    volumes:
      - mediawiki_images:/var/www/html/images  # Named volume for images
      # LocalSettings.php should be added after initial setup
    environment:
      MEDIAWIKI_DB_HOST: db  # Explicit DB host
      MEDIAWIKI_DB_TYPE: mariadb
      MEDIAWIKI_DB_NAME: wiki
      MEDIAWIKI_DB_USER: remo
      MEDIAWIKI_DB_PASSWORD: 1234asdf
    networks:
      - projekt-netzwerk

volumes:
  db_data:  # Proper volume declaration
  mediawiki_images:  # Volume for wiki images

networks:
  projekt-netzwerk:
    external: true
